[google_sheets]
type = "service_account"
project_id = "mago-marketing"
private_key_id = "65ef62211fa5fdf8cd8de73b4fae692feabd8421"
# ★重要: この private_key の値は、必ず「"""」で囲む必要があります。
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCht1hFvC8ocNGp
meWOgalpkyOkKf4yTyABR+MFU1hZbMa2Hc9YtqGQdTI3QSm9jodfzbCuZ/ViY3AL
wHdEo7c76MV9/inp0uuBWxN1II8DxHRLYWHV/uE7Dw3IYfNyBG/owZR3Mxnx3ut+
a6iVO4lnqp3Vneq8z/Lx1mpDsY5GZz6DKZE21LmN0WJDJFSCUtGkSzEzMZDvs2Tk
A16ghcquai/VYaaMGP7nmRYUhSYsSn3Y7S/W7rk9yWVHyT3UFgB1S1xOXyuTs3im
vB5NdGOGbFhw9+fLYvHCByjKujcc7pnyJYJvoy0CfkTBaYVBnOHtTr7L8uwNAdyM
EvdzfzC7AgMBAAECggEADdHNtNPikcmmWSCCKf3xnMiKrK47/0+ctA9RGrTnIWk2
x/xfKj0dLGufeXJTn1PNRMYemaDfquNFgXOWnaKB95gqPFyad1Vjc7/1Nzarkg5Z
Q9HUGwX3eGUOb/fS5oTzjUfxqIgQ6Qb8R+bqVqpqURYW+9jNZQo+QCVrGlLTjjeE
mZoeJxrrhN2v3t9LiEXUoL9OnmYl09WWPUaGJpGJJxA60zYShKdQgiSzdDhRJtts
uVw2h7MquEMWssPZ7E0BZmeEFx3Y4Pt9olJtXIBzh1yds2apoYyr7m+Wev+aU1bm
9RZhAj5KUo+679AOh9hzZF3JictrpFamQP7X7xqT0QKBgQDZXJAM07hNxxJAOypg
hgkwhq72N1CBCpGJtP5tEsrpmc8Bb0R/21v615SjyaK1Ldob81Jf3g+ZkgSzOmKR
hE65YbTZzLjVyXnJP9vmFK4cNTX8MxThClSO6tVNLPBfSfnGxsbFjl/vu8fJ+IFP
sFzLz5Pqur3NzlEb6DrYpwKriwKBgQC+dolwOADCuhkr1VJoG/K9Iej2CyJZSJoA
iQK64UecYT87UJDyjC2GLbgsrfLy2UAQIZRTmUJ6gBna/hX8aWzUsNuUAeSATue4
sIj5KvSsTLQJpIMxh3hpav9xfwWMc1fR0knSLOCjVjTG6cXjVtVjTmFPLxS8QNNT
+vDIwHD1kQKBgQCP/poPZVL7c53Ln2Z7e1ArLY5K3moeknnH2HeUmpaCGadKNAQV
D6TnkFmQB8waar3LNm6jw+BhxDII6ezSqevdM7UzdEQenNJpWDy9N4YAed/Bq7Vx
P/60jy2vas3y0nb+EEEuLxuEt8mrK02/FP7kpic/oWaMKNniuv4A+OLz8QKBgEIf
JNewmZMAyHxPMqyyBzNh8l54vxQAAHbvGeOHEjVYDXuqHKgXwjYy6R2Zxh5JDdSL
09KyAkJE9rTwQPHAJ+gu/gwEHC/vNMMJhoP6RbcLafVvB5zKSyNN4iCk2GhKItLV
DovIyLPr2aa0wd6K5snzDBVRYwF3/+XH2I/ZP14BAoGB ALLEJIdLW/cmdR2WmCsX
FHPeYZKXftXktMfTvbK1lKRY9iBeDtZ9VNSwte7k1skjjIEq0hvR9MU3sA1Hn88B
MZpmmp6Pw5weLIW5+x6Iy0D5VJAFmU6nknZUrBIiTJEWbRZ/9EtRw8ZbIAdsCDAB
G8tMx7OHS2MAbvRBvJcbOFl+
-----END PRIVATE KEY-----"""
client_email = "streamlit-app@mago-marketing.iam.gserviceaccount.com"
client_id = "110660036125264203940"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-app%40mago-marketing.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
